//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DbEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommerceEntities : DbContext
    {
        public ecommerceEntities()
            : base("name=ecommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<brand> brands { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<color> colors { get; set; }
        public DbSet<coupan> coupans { get; set; }
        public DbSet<deliverycharge> deliverycharges { get; set; }
        public DbSet<deliveryday> deliverydays { get; set; }
        public DbSet<image> images { get; set; }
        public DbSet<length> lengths { get; set; }
        public DbSet<newletter> newletters { get; set; }
        public DbSet<orderdetail> orderdetails { get; set; }
        public DbSet<orderheader> orderheaders { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<productpricing> productpricings { get; set; }
        public DbSet<review> reviews { get; set; }
        public DbSet<staticpage> staticpages { get; set; }
        public DbSet<user> users { get; set; }
    }
}
