//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliverycharge
    {
        public int id { get; set; }
        public Nullable<decimal> deliveryDoller { get; set; }
        public Nullable<decimal> freeDeliveryAmountPound { get; set; }
        public Nullable<decimal> deliveryPound { get; set; }
        public Nullable<decimal> freeDeliveryAmountEuro { get; set; }
        public Nullable<decimal> deliveryEuro { get; set; }
        public Nullable<decimal> freeDeliveryAmountNigria { get; set; }
        public Nullable<decimal> deliveryNigria { get; set; }
        public Nullable<decimal> freeDeliveryAmountAngola { get; set; }
        public Nullable<decimal> deliveryAngola { get; set; }
        public Nullable<decimal> freeDeliveryAmountGhana { get; set; }
        public Nullable<decimal> deliveryGhana { get; set; }
        public Nullable<decimal> freeDeliveryAmountDoller { get; set; }
        public string DeliveryDays { get; set; }
        public Nullable<bool> Default { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
