//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderheader
    {
        public int orderID { get; set; }
        public int Userid { get; set; }
        public string PermotionCode { get; set; }
        public string CurrencyChoosenByUser { get; set; }
        public decimal AmountInCurrencyChoosenByuser { get; set; }
        public string CurrencyInWhichAmmountPaid { get; set; }
        public decimal ActualAmountPaid { get; set; }
        public string PaymentStatus { get; set; }
        public string OrderStatus { get; set; }
        public string CreatedDate { get; set; }
        public decimal DeliveryCharges { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string DAddress1 { get; set; }
        public string DAddress2 { get; set; }
        public string DCity { get; set; }
        public string DState { get; set; }
        public string DPostCode { get; set; }
        public string DCountry { get; set; }
        public string TransId { get; set; }
        public Nullable<decimal> TotalProductCostInUserCurrency { get; set; }
        public Nullable<decimal> TotalProductCostInConvertedrCurrency { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string CreateDate { get; set; }
    }
}
