//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public Nullable<int> catid { get; set; }
        public string name { get; set; }
        public string discription { get; set; }
        public string image { get; set; }
        public Nullable<int> brandid { get; set; }
        public string productCode { get; set; }
        public string keyWord { get; set; }
        public Nullable<bool> isHot { get; set; }
    }
}
