//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class productpricing
    {
        public int id { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> lengthId { get; set; }
        public Nullable<int> colorId { get; set; }
        public decimal priceDollar { get; set; }
        public decimal priceeuro { get; set; }
        public decimal pricepound { get; set; }
        public decimal ourpriceDollar { get; set; }
        public decimal ourpriceeuro { get; set; }
        public decimal ourpricepound { get; set; }
        public decimal ourpricenigeria { get; set; }
        public decimal ourpriceangola { get; set; }
        public decimal ourpriceghana { get; set; }
        public decimal priceghana { get; set; }
        public decimal priceangola { get; set; }
        public decimal pricenigeria { get; set; }
    }
}
